server:
  port: 8082

spring:
  application:
    name: poc-client

andes:
  api:
    client:
      clients:
        orders:
          base-url: http://localhost:8082
          connect-timeout: 2s
          read-timeout: 5s
          correlation-id-enabled: true
          request-id-enabled: true

logging:
  level:
    pe.andes: DEBUG
