plugins {
    id 'java-library'
    id 'maven-publish'
    id 'jacoco'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'pe.edu.galaxy.training.java'
version = '3.0.3'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    withSourcesJar()
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

tasks.named('bootJar') {
    enabled = false
}
tasks.named('jar') {
    enabled = true
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:4.1.1"
        mavenBom "com.azure.spring:spring-cloud-azure-dependencies:7.4.0"
    }
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-aspectj'
    //api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.springframework:spring-tx'
    api 'com.fasterxml.jackson.core:jackson-databind'

    compileOnly 'org.springframework.boot:spring-boot-autoconfigure'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    // Service Bus se autentica solo con connection string (sin DefaultAzureCredential/az login)
    api 'com.azure:azure-messaging-servicebus'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    //testRuntimeOnly 'com.h2database:h2'
}

tasks.named('test') {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.group
            artifactId = 'oms-starter-audit-core'
            version = project.version
            // Mapea las versiones a sus valores resueltos
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionOf('runtimeClasspath')
                }
            }
        }
    }
    repositories {
        mavenLocal()
        maven {
            name = "nexus"
            boolean isSnapshot = version.toString().endsWith("SNAPSHOT")
            url = isSnapshot
                    ? "http://localhost:8089/repository/maven-snapshots/"
                    : "http://localhost:8089/repository/maven-releases/"
            allowInsecureProtocol = true
            credentials {
                username = findProperty('nexusUser')
                password = findProperty('nexusPassword')
            }
        }
    }
}
